util: fix test error with setupOpt
When running go tests, there was the following error:

```
test/dependencies/iptb/proc_unix.go:11: undefined: setupOpt
```

Let's make it simpler and just add a util/proc_windows.go where
setupOpt() is defined to do nothing.